### ISSUE TITLE
Phase E: 統合環境の動作確認 - 4層テスト戦略統合と最適化

### ISSUE THREAD

**Issue by usaganikki** [usaganikki/Web3DExplorer#74]
## 🎯 Phase E の目的

4層テスト戦略（QUnit + Jest + BackstopJS + Playwright）の統合環境を確立し、CI/CD連携とパフォーマンス最適化を完了する。

**親Issue**: #67 責任分離型テスト戦略の基盤環境構築
**推定工数**: 4-6時間
**依存関係**: Phase A〜D すべて完了後

### 統合環境構築
- [ ] 4層テストの統一実行コマンド作成
- [ ] 並列実行とシーケンシャル実行の最適化
- [ ] テスト結果の統合レポート生成
- [ ] エラーハンドリングとデバッグ環境整備

### CI/CD環境構築
- [ ] GitHub Actions ワークフロー設定
- [ ] 各フェーズの並列実行設定
- [ ] テスト失敗時の適切なエラーレポート
- [ ] アーティファクト（レポート・画像）の保存設定

### パフォーマンス測定・最適化
- [ ] 各テスト層の実行時間測定
- [ ] 目標時間内での実行確認
- [ ] ボトルネック特定と最適化
- [ ] メモリ使用量とリソース効率化

### ドキュメント作成
- [ ] TestStrategySetup.md - 環境構築手順書
- [ ] TestExecution.md - テスト実行ガイド
- [ ] TroubleshootingGuide.md - 問題解決ガイド
- [ ] CIConfig.md - CI/CD設定説明書

### 統合実行スクリプト例
```json
// package.json
{
  "scripts": {
    "test": "npm run test:all",
    "test:all": "npm run test:qunit && npm run test:jest && npm run test:visual && npm run test:e2e",
    "test:fast": "npm run test:qunit && npm run test:jest",
    "test:visual-regression": "npm run test:visual && npm run test:e2e",
    "test:qunit": "qunit tests/qunit/**/*.test.js",
    "test:jest": "jest --config jest.config.js",
    "test:visual": "backstop test",
    "test:visual:approve": "backstop approve",
    "test:e2e": "playwright test",
    "test:e2e:headed": "playwright test --headed",
    "test:e2e:debug": "playwright test --debug",
    "test:ci": "npm run test:fast && npm run test:visual && npm run test:e2e:ci",
    "test:e2e:ci": "playwright test --workers=1",
    "test:report": "npm run generate-test-report"
  }
}
```

### GitHub Actions ワークフロー例
```yaml
# .github/workflows/test-strategy.yml
name: 責任分離型テスト戦略

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  fast-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run QUnit Tests
        run: npm run test:qunit
      
      - name: Run Jest Tests
        run: npm run test:jest
        
      - name: Upload Jest Coverage
        uses: actions/upload-artifact@v4
        with:
          name: jest-coverage
          path: coverage/

  visual-tests:
    runs-on: ubuntu-latest
    needs: fast-tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright
        run: npx playwright install
      
      - name: Start dev server
        run: npm run dev &
        
      - name: Wait for server
        run: npx wait-on http://localhost:3000
      
      - name: Run Visual Regression Tests
        run: npm run test:visual
        
      - name: Upload Visual Test Results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: visual-test-results
          path: tests/visual/

  e2e-tests:
    runs-on: ubuntu-latest
    needs: visual-tests
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright
        run: npx playwright install
      
      - name: Run E2E Tests
        run: npx playwright test --project=${{ matrix.browser }}
        
      - name: Upload E2E Results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: e2e-results-${{ matrix.browser }}
          path: tests/e2e/reports/
```

### テスト実行時間監視スクリプト例
```typescript
// scripts/test-performance-monitor.ts
interface TestMetrics {
  phase: string;
  duration: number;
  target: number;
  status: 'pass' | 'warning' | 'fail';
}

export class TestPerformanceMonitor {
  private metrics: TestMetrics[] = [];

  async measurePhase(phase: string, target: number, testFn: () => Promise<void>): Promise<void> {
    const startTime = Date.now();
    
    try {
      await testFn();
      const duration = Date.now() - startTime;
      
      let status: 'pass' | 'warning' | 'fail' = 'pass';
      if (duration > target * 1.5) status = 'fail';
      else if (duration > target) status = 'warning';
      
      this.metrics.push({ phase, duration, target, status });
      
      console.log(`✅ ${phase}: ${duration}ms (target: ${target}ms) - ${status}`);
    } catch (error) {
      console.error(`❌ ${phase}: Failed - ${error}`);
      throw error;
    }
  }

  generateReport(): void {
    console.log('\n📊 テスト実行時間レポート');
    console.log('================================');
    
    this.metrics.forEach(metric => {
      const icon = metric.status === 'pass' ? '✅' : metric.status === 'warning' ? '⚠️' : '❌';
      console.log(`${icon} ${metric.phase}: ${metric.duration}ms / ${metric.target}ms`);
    });
    
    const totalDuration = this.metrics.reduce((sum, m) => sum + m.duration, 0);
    console.log(`\n⏱️ 総実行時間: ${totalDuration}ms`);
  }
}
```

### 統合環境確認
- [ ] 4層すべてのテストが単一コマンドで実行される
- [ ] テスト失敗時に適切なエラーメッセージが表示される
- [ ] 統合レポートが正常に生成される
- [ ] デバッグモードが各層で正常に動作する

### CI/CD動作確認
- [ ] GitHub Actionsで自動実行される
- [ ] プルリクエスト時にテストが実行される
- [ ] 並列実行が効率的に動作する
- [ ] アーティファクトが適切に保存される

### パフォーマンス目標達成
- [ ] QUnit: 1ms/test以下で実行される
- [ ] Jest: 10-50ms/test範囲内で実行される
- [ ] BackstopJS: 1-5秒/test範囲内で実行される
- [ ] Playwright E2E: 10-30秒/test範囲内で実行される

### ドキュメント完成
- [ ] 環境構築手順書が完成している
- [ ] テスト実行ガイドが完成している
- [ ] 問題解決ガイドが完成している
- [ ] CI/CD設定説明書が完成している

### 技術的成果
- ✅ 4層テスト戦略の完全稼働環境
- ✅ CI/CD統合による自動品質保証
- ✅ Three.js特化のテストフレームワーク基盤
- ✅ 責任分離による効率的テスト実行

### 運用的成果
- ✅ 大幅なテスト実行時間短縮
- ✅ 視覚的品質保証の自動化
- ✅ クロスブラウザ対応の確実性
- ✅ 開発効率とコード品質の向上

## 🔗 全Phase統合

完成した4層テスト戦略：
```
Layer 1: QUnit (1ms/test)       → 数学計算の正確性
Layer 2: Jest (10-50ms/test)    → UIロジックの動作
Layer 3: BackstopJS (1-5s/test) → 視覚的品質保証
Layer 4: Playwright (10-30s/test) → ユーザー体験検証
```

## 🚀 次のステップ

Phase E完了後、実際のテストケース実装Issueに進む準備が整います。

## ⚠️ 重要な確認項目

- すべてのテスト層が独立して動作すること
- CI環境での安定性確保
- 実行時間が許容範囲内であること
- ドキュメントが実用的であること
- 次の開発チームが引き継ぎ可能であること

### 環境確認
- [ ] ローカル開発環境での4層テスト実行
- [ ] CI環境での自動テスト実行
- [ ] エラー時の適切なフィードバック

### ドキュメント確認
- [ ] 新規開発者が環境構築可能
- [ ] テスト実行手順が明確
- [ ] トラブルシューティングが実用的

### 引き継ぎ準備
- [ ] 設定ファイルがすべて整備済み
- [ ] コマンド体系が統一済み
- [ ] 次Phase実装の準備完了
